#Redhat8 UBIを指定してベースイメージを作成
#FROM	registry.access.redhat.com/ubi8/ubi
FROM    centos:7 
MAINTAINER CTL

#nginx連携用ポートオープン
EXPOSE 8080
#PostgreSQL用ポートオープン
EXPOSE 5432

#DevaaS2.0環境はProxyサーバを参照しているため、yum.confに設定を追加
RUN echo proxy=http://10.166.28.250:8080 >> /etc/yum.conf

#RUN cat /etc/yum.conf

#dnf 更新・アップグレードを実行後、Redhat OpenJDKをインストール
RUN yum -y update && yum -y upgrade && yum install -y java-1.8.0-openjdk

#インストールしたJavaのバージョン表示
RUN java -version

#ホストからapache-tomcat-9.0.36.tar.gzをコンテナ内に展開しながら格納
ADD apache-tomcat-9.0.36.tar.gz /opt/

#Tomcatのフォルダ名を変更
RUN cd /opt && mv apache-tomcat-9.0.36 tomcat

#confフォルダをバックアップ
RUN cp -r /opt/tomcat/conf/ /opt/tomcat/conf_bk/

#webappsフォルダをバックアップ
RUN cp -r /opt/tomcat/webapps/ /opt/tomcat/webapps_bk/

#Tomcatを起動
#CMD ["/opt/tomcat/bin/catalina.sh", "run"]


